	tilepal 0, GRAY, YELLOW, GREEN, RED, GRAY, GRAY, RED, RED
	tilepal 0, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, GRAY, GRAY
	tilepal 0, ROOF, GRAY, GRAY, GRAY, RED, RED, RED, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, RED, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, RED, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, YELLOW, YELLOW

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
