INCLUDE "constants.asm"


; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in layout.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

HoOhFrontpic:        INCBIN "gfx/pokemon/ho_oh/front.animated.2bpp.lz"
StelloceanFrontpic:     INCBIN "gfx/pokemon/stellocean/front.animated.2bpp.lz"
MtNootFrontpic:   INCBIN "gfx/pokemon/mt_noot/front.animated.2bpp.lz"
UrskimoFrontpic:  	 INCBIN "gfx/pokemon/urskimo/front.animated.2bpp.lz"
SwimianFrontpic:    INCBIN "gfx/pokemon/swimian/front.animated.2bpp.lz"
RaikouFrontpic:      INCBIN "gfx/pokemon/raikou/front.animated.2bpp.lz"
AvatriceFrontpic:       INCBIN "gfx/pokemon/avatrice/front.animated.2bpp.lz"
ArticunoFrontpic:    INCBIN "gfx/pokemon/articuno/front.animated.2bpp.lz"
TaurosFrontpic:      INCBIN "gfx/pokemon/tauros/front.animated.2bpp.lz"
VenusaurFrontpic:    INCBIN "gfx/pokemon/venusaur/front.animated.2bpp.lz"
SlaatelFrontpic:       INCBIN "gfx/pokemon/slaatel/front.animated.2bpp.lz"
RyunariFrontpic:     INCBIN "gfx/pokemon/ryunari/front.animated.2bpp.lz"
ScorchopprFrontpic:  INCBIN "gfx/pokemon/scorchoppr/front.animated.2bpp.lz"
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
LamseedFrontpic:      INCBIN "gfx/pokemon/lamseed/front.animated.2bpp.lz"
YukittenBackpic:     INCBIN "gfx/pokemon/yukitten/back.2bpp.lz"
PorygonBackpic:      INCBIN "gfx/pokemon/porygon/back.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"



SECTION "Pics 2", ROMX

BlastoiseFrontpic:   INCBIN "gfx/pokemon/blastoise/front.animated.2bpp.lz"
MajesdorFrontpic:    INCBIN "gfx/pokemon/majesdor/front.animated.2bpp.lz"
OkamikazeFrontpic:   INCBIN "gfx/pokemon/okamikaze/front.animated.2bpp.lz"
OnionionFrontpic:   INCBIN "gfx/pokemon/onionion/front.animated.2bpp.lz"
MothoFrontpic:   INCBIN "gfx/pokemon/motho/front.animated.2bpp.lz"
YagagarasuFrontpic:      INCBIN "gfx/pokemon/yagagarasu/front.animated.2bpp.lz"
NoxromaeusFrontpic:  INCBIN "gfx/pokemon/noxromaeus/front.animated.2bpp.lz"
BiporkarFrontpic:    INCBIN "gfx/pokemon/biporkar/front.animated.2bpp.lz"
SnokageFrontpic:   INCBIN "gfx/pokemon/snokage/front.animated.2bpp.lz"
BlazenbullFrontpic:     INCBIN "gfx/pokemon/blazenbull/front.animated.2bpp.lz"
ZapdosFrontpic:      INCBIN "gfx/pokemon/zapdos/front.animated.2bpp.lz"
IgnagaFrontpic:       INCBIN "gfx/pokemon/ignaga/front.animated.2bpp.lz"
Ma_0Frontpic:      INCBIN "gfx/pokemon/ma_0/front.animated.2bpp.lz"
QwallopFrontpic:     INCBIN "gfx/pokemon/qwallop/front.animated.2bpp.lz"
CharizardFrontpic:   INCBIN "gfx/pokemon/charizard/front.animated.2bpp.lz"
ScaulterFrontpic:    INCBIN "gfx/pokemon/scaulter/front.animated.2bpp.lz"
NuckawheezBackpic:     INCBIN "gfx/pokemon/nuckawheez/back.2bpp.lz"
MurdermisBackpic:      INCBIN "gfx/pokemon/murdermis/back.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/morty.2bpp.lz"
KodoroyahBackpic:       INCBIN "gfx/pokemon/kodoroyah/back.2bpp.lz"
BreederMPic:			INCBIN "gfx/trainers/breeder_m.2bpp.lz"
DemonPic:				INCBIN "gfx/trainers/demon.2bpp.lz"


SECTION "Pics 3", ROMX

WirigibleFrontpic:     INCBIN "gfx/pokemon/wirigible/front.animated.2bpp.lz"
VoltingerFrontpic:    INCBIN "gfx/pokemon/voltinger/front.animated.2bpp.lz"
GyaradosFrontpic:    INCBIN "gfx/pokemon/gyarados/front.animated.2bpp.lz"
GeneropsisFrontpic:  INCBIN "gfx/pokemon/generopsis/front.animated.2bpp.lz"
TendrillFrontpic:      INCBIN "gfx/pokemon/tendrill/front.animated.2bpp.lz"
ExotunityFrontpic:     INCBIN "gfx/pokemon/exotunity/front.animated.2bpp.lz"
CuttleFrontpic:     INCBIN "gfx/pokemon/cuttle/front.animated.2bpp.lz"
HornampaFrontpic:     INCBIN "gfx/pokemon/hornampa/front.animated.2bpp.lz"
SlowbroFrontpic:     INCBIN "gfx/pokemon/slowbro/front.animated.2bpp.lz"
VazzinateFrontpic:  INCBIN "gfx/pokemon/vazzinate/front.animated.2bpp.lz"
SakuronnaFrontpic:     INCBIN "gfx/pokemon/sakuronna/front.animated.2bpp.lz"
CloysterFrontpic:    INCBIN "gfx/pokemon/cloyster/front.animated.2bpp.lz"
SnosebleedFrontpic:    INCBIN "gfx/pokemon/snosebleed/front.animated.2bpp.lz"
JaddiceFrontpic:     INCBIN "gfx/pokemon/jaddice/front.animated.2bpp.lz"
GnomercyFrontpic:  INCBIN "gfx/pokemon/gnomercy/front.animated.2bpp.lz"
RaichuFrontpic:      INCBIN "gfx/pokemon/raichu/front.animated.2bpp.lz"
BobbitrapFrontpic:    INCBIN "gfx/pokemon/bobbitrap/front.animated.2bpp.lz"
BehemothraBackpic:      INCBIN "gfx/pokemon/behemothra/back.2bpp.lz"


SECTION "Pics 4", ROMX

DodrioFrontpic:      INCBIN "gfx/pokemon/dodrio/front.animated.2bpp.lz"
TidoFrontpic:    INCBIN "gfx/pokemon/tido/front.animated.2bpp.lz"
HitmontopFrontpic:   INCBIN "gfx/pokemon/hitmontop/front.animated.2bpp.lz"
MoradayFrontpic:        INCBIN "gfx/pokemon/moraday/front.animated.2bpp.lz"
OdditullyFrontpic:     INCBIN "gfx/pokemon/odditully/front.animated.2bpp.lz"
NimbocetusFrontpic:     INCBIN "gfx/pokemon/nimbocetus/front.animated.2bpp.lz"
DragoniteFrontpic:   INCBIN "gfx/pokemon/dragonite/front.animated.2bpp.lz"
YuggromiFrontpic:   		INCBIN "gfx/pokemon/yuggromi/front.animated.2bpp.lz"
BowlideFrontpic:     		INCBIN "gfx/pokemon/bowlide/front.animated.2bpp.lz"
AerodactylFrontpic:  		INCBIN "gfx/pokemon/aerodactyl/front.animated.2bpp.lz"
GanzerkerFrontpic:     		INCBIN "gfx/pokemon/ganzerker/front.animated.2bpp.lz"
ZeppliumFrontpic:         	INCBIN "gfx/pokemon/zepplium/front.animated.2bpp.lz"
NanuquaFrontpic:     		INCBIN "gfx/pokemon/nanuqua/front.animated.2bpp.lz"
MossarreFrontpic:       	INCBIN "gfx/pokemon/mossarre/front.animated.2bpp.lz"
ShrimpanziFrontpic:    		INCBIN "gfx/pokemon/shrimpanzi/front.animated.2bpp.lz"
DunefinFrontpic:   			INCBIN "gfx/pokemon/dunefin/front.animated.2bpp.lz"
JolteonFrontpic:     		INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
MoneumennFrontpic:     		INCBIN "gfx/pokemon/moneumenn/front.animated.2bpp.lz"
BermudantFrontpic:      	INCBIN "gfx/pokemon/bermudant/front.animated.2bpp.lz"
UnownEFrontpic:     	 	INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"


SECTION "Pics 5", ROMX

ScorperorFrontpic:      INCBIN "gfx/pokemon/scorperor/front.animated.2bpp.lz"
PepofferFrontpic:     INCBIN "gfx/pokemon/pepoffer/front.animated.2bpp.lz"
CantaloneFrontpic:   INCBIN "gfx/pokemon/cantalone/front.animated.2bpp.lz"
CasanocteFrontpic:    INCBIN "gfx/pokemon/casanocte/front.animated.2bpp.lz"
JunobeFrontpic:     INCBIN "gfx/pokemon/junobe/front.animated.2bpp.lz"
MissingnoFrontpic:   INCBIN "gfx/pokemon/missingno/front.animated.2bpp.lz"
NomsabreFrontpic:    INCBIN "gfx/pokemon/nomsabre/front.animated.2bpp.lz"
PripydermFrontpic:    INCBIN "gfx/pokemon/pripyderm/front.animated.2bpp.lz"
PolitoedFrontpic:    INCBIN "gfx/pokemon/politoed/front.animated.2bpp.lz"
GiguardFrontpic:  INCBIN "gfx/pokemon/giguard/front.animated.2bpp.lz"
KrakentoaFrontpic:     INCBIN "gfx/pokemon/krakentoa/front.animated.2bpp.lz"
SappuraFrontpic:   INCBIN "gfx/pokemon/sappura/front.animated.2bpp.lz"
NavigazerFrontpic:     INCBIN "gfx/pokemon/navigazer/front.animated.2bpp.lz"
CharmeleonFrontpic:  INCBIN "gfx/pokemon/charmeleon/front.animated.2bpp.lz"
BundegrafFrontpic:     INCBIN "gfx/pokemon/bundegraf/front.animated.2bpp.lz"
CantogethaFrontpic:   INCBIN "gfx/pokemon/cantogetha/front.animated.2bpp.lz"
FluffruitFrontpic:      INCBIN "gfx/pokemon/fluffruit/front.animated.2bpp.lz"
SateliskFrontpic:   INCBIN "gfx/pokemon/satelisk/front.animated.2bpp.lz"
ParasectFrontpic:    INCBIN "gfx/pokemon/parasect/front.animated.2bpp.lz"
PeacolderFrontpic:      INCBIN "gfx/pokemon/peacolder/front.animated.2bpp.lz"
HeracrossFrontpic:   INCBIN "gfx/pokemon/heracross/front.animated.2bpp.lz"
NursePic:			INCBIN "gfx/trainers/nurse.2bpp.lz"
BillPic:			INCBIN "gfx/trainers/bill.2bpp.lz"
MutantPic:			INCBIN "gfx/trainers/mutant.2bpp.lz"


SECTION "Pics 6", ROMX

GrubboidFrontpic:     INCBIN "gfx/pokemon/grubboid/front.animated.2bpp.lz"
MurdermisFrontpic:     INCBIN "gfx/pokemon/murdermis/front.animated.2bpp.lz"
WartortleFrontpic:   INCBIN "gfx/pokemon/wartortle/front.animated.2bpp.lz"
MandelblobFrontpic:      INCBIN "gfx/pokemon/mandelblob/front.animated.2bpp.lz"
CairnivoreFrontpic:       INCBIN "gfx/pokemon/cairnivore/front.animated.2bpp.lz"
AmanigoFrontpic:   INCBIN "gfx/pokemon/amanigo/front.animated.2bpp.lz"
SmothereneFrontpic:    INCBIN "gfx/pokemon/smotherene/front.animated.2bpp.lz"
SnoverdoseFrontpic:    INCBIN "gfx/pokemon/snoverdose/front.animated.2bpp.lz"
SubcerosFrontpic:    INCBIN "gfx/pokemon/subceros/front.animated.2bpp.lz"
AmpharosFrontpic:    INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
OnioniFrontpic:    INCBIN "gfx/pokemon/onioni/front.animated.2bpp.lz"
FlareonFrontpic:     INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
FarfetchDFrontpic:   INCBIN "gfx/pokemon/farfetch_d/front.animated.2bpp.lz"
PocalyptusFrontpic:   INCBIN "gfx/pokemon/pocalyptus/front.animated.2bpp.lz"
TobacoonFrontpic:     INCBIN "gfx/pokemon/tobacoon/front.animated.2bpp.lz"
GigeratorFrontpic:      INCBIN "gfx/pokemon/gigerator/front.animated.2bpp.lz"
TentacruelFrontpic:  INCBIN "gfx/pokemon/tentacruel/front.animated.2bpp.lz"
ElekidFrontpic:      INCBIN "gfx/pokemon/elekid/front.animated.2bpp.lz"
MeowtainFrontpic:    INCBIN "gfx/pokemon/meowtain/front.animated.2bpp.lz"
KalkolaFrontpic:     INCBIN "gfx/pokemon/kalkola/front.animated.2bpp.lz"
VulpixFrontpic:      INCBIN "gfx/pokemon/vulpix/front.animated.2bpp.lz"
WiwrightFrontpic:      INCBIN "gfx/pokemon/wiwright/front.animated.2bpp.lz"
AttackoFrontpic:   INCBIN "gfx/pokemon/attacko/front.animated.2bpp.lz"
NomsterBackpic:      INCBIN "gfx/pokemon/nomster/back.2bpp.lz" ;orig rattata
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
WillPic:             INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
MagnemiteFrontpic:   INCBIN "gfx/pokemon/magnemite/front.animated.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
MagnemiteBackpic:    INCBIN "gfx/pokemon/magnemite/back.2bpp.lz"
MastermindPic:			INCBIN "gfx/trainers/mastermind.2bpp.lz"


SECTION "Pics 7", ROMX

GanzorahFrontpic:    INCBIN "gfx/pokemon/ganzorah/front.animated.2bpp.lz"
SwazzageFrontpic:   INCBIN "gfx/pokemon/swazzage/front.animated.2bpp.lz"
EelkieFrontpic:     INCBIN "gfx/pokemon/eelkie/front.animated.2bpp.lz"
SneaselFrontpic:     INCBIN "gfx/pokemon/sneasel/front.animated.2bpp.lz"
PlantennaFrontpic:   INCBIN "gfx/pokemon/plantenna/front.animated.2bpp.lz"
TherazorFrontpic:     INCBIN "gfx/pokemon/therazor/front.animated.2bpp.lz"
IcosahedFrontpic:  INCBIN "gfx/pokemon/icosahed/front.animated.2bpp.lz"
ArasbestosFrontpic:       INCBIN "gfx/pokemon/arasbestos/front.animated.2bpp.lz"
EyechosisFrontpic:    INCBIN "gfx/pokemon/eyechosis/front.animated.2bpp.lz"
FelioritteFrontpic:    INCBIN "gfx/pokemon/felioritte/front.animated.2bpp.lz"
MoperdorFrontpic:      INCBIN "gfx/pokemon/moperdor/front.animated.2bpp.lz"
BismuttFrontpic:     INCBIN "gfx/pokemon/bismutt/front.animated.2bpp.lz"
DolmesaFrontpic:    INCBIN "gfx/pokemon/dolmesa/front.animated.2bpp.lz"
PeekeyeFrontpic:     INCBIN "gfx/pokemon/peekeye/front.animated.2bpp.lz"
FurdobaFrontpic:   INCBIN "gfx/pokemon/furdoba/front.animated.2bpp.lz"
WormeekFrontpic:      INCBIN "gfx/pokemon/wormeek/front.animated.2bpp.lz"
PitayrantFrontpic:      INCBIN "gfx/pokemon/pitayrant/front.animated.2bpp.lz"
BehemothraFrontpic:     INCBIN "gfx/pokemon/behemothra/front.animated.2bpp.lz"
VegetebaaFrontpic:   INCBIN "gfx/pokemon/vegetebaa/front.animated.2bpp.lz"
MumagnusFrontpic:     INCBIN "gfx/pokemon/mumagnus/front.animated.2bpp.lz"
MagnetonFrontpic:    INCBIN "gfx/pokemon/magneton/front.animated.2bpp.lz"
DragonairFrontpic:   INCBIN "gfx/pokemon/dragonair/front.animated.2bpp.lz"
ForretressFrontpic:  INCBIN "gfx/pokemon/forretress/front.animated.2bpp.lz"
AllseeraphFrontpic:     INCBIN "gfx/pokemon/allseeraph/front.animated.2bpp.lz"
GeneropsisBackpic:   INCBIN "gfx/pokemon/generopsis/back.2bpp.lz"
BreederFPic:			INCBIN "gfx/trainers/breeder_f.2bpp.lz"


SECTION "Pics 8", ROMX

CaddisicleFrontpic:        INCBIN "gfx/pokemon/caddisicle/front.animated.2bpp.lz"
CrobatFrontpic:      INCBIN "gfx/pokemon/crobat/front.animated.2bpp.lz"
CalarmouriFrontpic:     INCBIN "gfx/pokemon/calarmouri/front.animated.2bpp.lz"
AntpyreFrontpic:     INCBIN "gfx/pokemon/antpyre/front.animated.2bpp.lz"
ZasterFrontpic:    INCBIN "gfx/pokemon/zaster/front.animated.2bpp.lz"
GrimpactFrontpic:    INCBIN "gfx/pokemon/grimpact/front.animated.2bpp.lz"
DrassalFrontpic:     INCBIN "gfx/pokemon/drassal/front.animated.2bpp.lz"
ScruffruitFrontpic:     INCBIN "gfx/pokemon/scruffruit/front.animated.2bpp.lz"
BrigadoomFrontpic:    INCBIN "gfx/pokemon/brigadoom/front.animated.2bpp.lz"
UmbreonFrontpic:     INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
CigerillarFrontpic:  INCBIN "gfx/pokemon/cigerillar/front.animated.2bpp.lz" ;orig chiko
GoosaplingFrontpic:     INCBIN "gfx/pokemon/goosapling/front.animated.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
SqueenieFrontpic:        INCBIN "gfx/pokemon/squeenie/front.animated.2bpp.lz"
MewFrontpic:         INCBIN "gfx/pokemon/mew/front.animated.2bpp.lz"
SidficiousFrontpic:   INCBIN "gfx/pokemon/sidficious/front.animated.2bpp.lz"
ClibbleFrontpic:        INCBIN "gfx/pokemon/clibble/front.animated.2bpp.lz"
RespectreFrontpic:   INCBIN "gfx/pokemon/respectre/front.animated.2bpp.lz"
DelibirdFrontpic:    INCBIN "gfx/pokemon/delibird/front.animated.2bpp.lz"
WormachoFrontpic:      INCBIN "gfx/pokemon/wormacho/front.animated.2bpp.lz"
KoaganFrontpic:       INCBIN "gfx/pokemon/koagan/front.animated.2bpp.lz"
YuefoeFrontpic:     INCBIN "gfx/pokemon/yuefoe/front.animated.2bpp.lz"
IvysaurFrontpic:     INCBIN "gfx/pokemon/ivysaur/front.animated.2bpp.lz"
PurraatzleFrontpic:      INCBIN "gfx/pokemon/purraatzle/front.animated.2bpp.lz"
RadeonFrontpic:      INCBIN "gfx/pokemon/radeon/front.animated.2bpp.lz"
MothomenFrontpic:  INCBIN "gfx/pokemon/mothomen/front.animated.2bpp.lz"
AstrotomFrontpic:    INCBIN "gfx/pokemon/astrotom/front.animated.2bpp.lz"


SECTION "Pics 9", ROMX

WyrmometerFrontpic:       INCBIN "gfx/pokemon/wyrmometer/front.animated.2bpp.lz"
PardnerFrontpic:   INCBIN "gfx/pokemon/pardner/front.animated.2bpp.lz"
PikachuFrontpic:     INCBIN "gfx/pokemon/pikachu/front.animated.2bpp.lz"
MadrugasaFrontpic:      INCBIN "gfx/pokemon/madrugasa/front.animated.2bpp.lz"
MagbyFrontpic:       INCBIN "gfx/pokemon/magby/front.animated.2bpp.lz"
OrgnomeFrontpic:  INCBIN "gfx/pokemon/orgnome/front.animated.2bpp.lz"
FursaFrontpic:       INCBIN "gfx/pokemon/fursa/front.animated.2bpp.lz"   ;orig totodile
BaafometFrontpic:     INCBIN "gfx/pokemon/baafomet/front.animated.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
UpwhaleFrontpic:      INCBIN "gfx/pokemon/upwhale/front.animated.2bpp.lz"
StranglureFrontpic:    INCBIN "gfx/pokemon/stranglure/front.animated.2bpp.lz"
NomsterFrontpic:     INCBIN "gfx/pokemon/nomster/front.animated.2bpp.lz" ;orig rattata
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
QwailFrontpic:     INCBIN "gfx/pokemon/qwail/front.animated.2bpp.lz"
MagikarpFrontpic:    INCBIN "gfx/pokemon/magikarp/front.animated.2bpp.lz"
CharmanderFrontpic:  INCBIN "gfx/pokemon/charmander/front.animated.2bpp.lz"
CocacobraFrontpic:      INCBIN "gfx/pokemon/cocacobra/front.animated.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
PrawmateFrontpic:    INCBIN "gfx/pokemon/prawmate/front.animated.2bpp.lz"
PorygonFrontpic:     INCBIN "gfx/pokemon/porygon/front.animated.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
DumbloonFrontpic:      INCBIN "gfx/pokemon/dumbloon/front.animated.2bpp.lz"
PeautyFrontpic:      INCBIN "gfx/pokemon/peauty/front.animated.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
TodescoolFrontpic:      INCBIN "gfx/pokemon/todescool/front.animated.2bpp.lz"
PolyroFrontpic:    INCBIN "gfx/pokemon/polyro/front.animated.2bpp.lz"
SandolphFrontpic:   INCBIN "gfx/pokemon/sandolph/front.animated.2bpp.lz"
SprunnyFrontpic:    INCBIN "gfx/pokemon/sprunny/front.animated.2bpp.lz"
FurnitFrontpic:      INCBIN "gfx/pokemon/furnit/front.animated.2bpp.lz"
ParasectBackpic:     INCBIN "gfx/pokemon/parasect/back.2bpp.lz"


SECTION "Pics 10", ROMX

MaulzerFrontpic:  INCBIN "gfx/pokemon/maulzer/front.animated.2bpp.lz"
SnowupFrontpic:    INCBIN "gfx/pokemon/snowup/front.animated.2bpp.lz"
BobbiteFrontpic:      INCBIN "gfx/pokemon/bobbite/front.animated.2bpp.lz"
TentaquilFrontpic:      INCBIN "gfx/pokemon/tentaquil/front.animated.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
ShreddrakeFrontpic:      INCBIN "gfx/pokemon/shreddrake/front.animated.2bpp.lz"
LanatunFrontpic:      INCBIN "gfx/pokemon/lanatun/front.animated.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
HexahedFrontpic:  INCBIN "gfx/pokemon/hexahed/front.animated.2bpp.lz"
ParasFrontpic:       INCBIN "gfx/pokemon/paras/front.animated.2bpp.lz"
SwimianBackpic:     INCBIN "gfx/pokemon/swimian/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
VoyapodFrontpic:     INCBIN "gfx/pokemon/voyapod/front.animated.2bpp.lz"
SquirtleFrontpic:    INCBIN "gfx/pokemon/squirtle/front.animated.2bpp.lz"
StelloceanBackpic:      INCBIN "gfx/pokemon/stellocean/back.2bpp.lz"
LeaffigyFrontpic:     INCBIN "gfx/pokemon/leaffigy/front.animated.2bpp.lz"
ElephootFrontpic:     INCBIN "gfx/pokemon/elephoot/front.animated.2bpp.lz"
CantogethaBackpic:    INCBIN "gfx/pokemon/cantogetha/back.2bpp.lz"
ShamselFrontpic:     INCBIN "gfx/pokemon/shamsel/front.animated.2bpp.lz"
TyrogueFrontpic:     INCBIN "gfx/pokemon/tyrogue/front.animated.2bpp.lz"
PurrdleFrontpic:    INCBIN "gfx/pokemon/purrdle/front.animated.2bpp.lz"
YuesbiFrontpic:      INCBIN "gfx/pokemon/yuesbi/front.animated.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/chuck.2bpp.lz"
NoomsdayFrontpic:       INCBIN "gfx/pokemon/noomsday/front.animated.2bpp.lz"
VazzinateBackpic:   INCBIN "gfx/pokemon/vazzinate/back.2bpp.lz"
StinpeonFrontpic:       INCBIN "gfx/pokemon/stinpeon/front.animated.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
VoltingerBackpic:     INCBIN "gfx/pokemon/voltinger/back.2bpp.lz"
HoplaqueFrontpic:       INCBIN "gfx/pokemon/hoplaque/front.animated.2bpp.lz"
AmbinniFrontpic:        INCBIN "gfx/pokemon/ambinni/front.animated.2bpp.lz"
HitmontopBackpic:    INCBIN "gfx/pokemon/hitmontop/back.2bpp.lz"
CloysterBackpic:     INCBIN "gfx/pokemon/cloyster/back.2bpp.lz"
NuckawheezFrontpic:    INCBIN "gfx/pokemon/nuckawheez/front.animated.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"
KaijuPic:			INCBIN "gfx/trainers/kaiju.2bpp.lz"


SECTION "Pics 11", ROMX

DodrioBackpic:       INCBIN "gfx/pokemon/dodrio/back.2bpp.lz"
NyalleyFrontpic:    INCBIN "gfx/pokemon/nyalley/front.animated.2bpp.lz"
KodoroyahFrontpic:      INCBIN "gfx/pokemon/kodoroyah/front.animated.2bpp.lz"
HappigFrontpic:   INCBIN "gfx/pokemon/happig/front.animated.2bpp.lz"
MissteriaFrontpic:    INCBIN "gfx/pokemon/missteria/front.animated.2bpp.lz"
SmoochumFrontpic:    INCBIN "gfx/pokemon/smoochum/front.animated.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
HabbleFrontpic:      INCBIN "gfx/pokemon/habble/front.animated.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
PripydermBackpic:     INCBIN "gfx/pokemon/pripyderm/back.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/clair.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
MammothraFrontpic:     INCBIN "gfx/pokemon/mammothra/front.animated.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
FlurikenFrontpic:     INCBIN "gfx/pokemon/fluriken/front.animated.2bpp.lz"
LawnieFrontpic:  INCBIN "gfx/pokemon/lawnie/front.animated.2bpp.lz"
ShellderFrontpic:    INCBIN "gfx/pokemon/shellder/front.animated.2bpp.lz"
TentacoolFrontpic:   INCBIN "gfx/pokemon/tentacool/front.animated.2bpp.lz"
NimboremFrontpic:      INCBIN "gfx/pokemon/nimborem/front.animated.2bpp.lz"
GyaradosBackpic:     INCBIN "gfx/pokemon/gyarados/back.2bpp.lz"
MtNootBackpic:    INCBIN "gfx/pokemon/mt_noot/back.2bpp.lz"
ArasbestosBackpic:        INCBIN "gfx/pokemon/arasbestos/back.2bpp.lz"
BermudantBackpic:       INCBIN "gfx/pokemon/bermudant/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
FelioritteBackpic:     INCBIN "gfx/pokemon/felioritte/back.2bpp.lz"
DoduoFrontpic:       INCBIN "gfx/pokemon/doduo/front.animated.2bpp.lz"
UrskimoBackpic:  	 INCBIN "gfx/pokemon/urskimo/back.2bpp.lz"
DratiniFrontpic:     INCBIN "gfx/pokemon/dratini/front.animated.2bpp.lz"
MagnetonBackpic:     INCBIN "gfx/pokemon/magneton/back.2bpp.lz"
PekoiFrontpic:    INCBIN "gfx/pokemon/pekoi/front.animated.2bpp.lz"
RyunariBackpic:      INCBIN "gfx/pokemon/ryunari/back.2bpp.lz"
TidoBackpic:     INCBIN "gfx/pokemon/tido/back.2bpp.lz"
ElekidBackpic:       INCBIN "gfx/pokemon/elekid/back.2bpp.lz"
TentaquilBackpic:       INCBIN "gfx/pokemon/tentaquil/back.2bpp.lz"
LanatunBackpic:       INCBIN "gfx/pokemon/lanatun/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
TherazorBackpic:      INCBIN "gfx/pokemon/therazor/back.2bpp.lz"
GuruPic: 			INCBIN "gfx/trainers/guru.2bpp.lz"
DelinquentMPic:		  INCBIN "gfx/trainers/delinquent_m.2bpp.lz"
DelinquentFPic:		  INCBIN "gfx/trainers/delinquent_f.2bpp.lz"


SECTION "Pics 12", ROMX

VenusaurBackpic:     INCBIN "gfx/pokemon/venusaur/back.2bpp.lz"
BlazenbullBackpic:      INCBIN "gfx/pokemon/blazenbull/back.2bpp.lz"
BrigadoomBackpic:     INCBIN "gfx/pokemon/brigadoom/back.2bpp.lz"
ObelithFrontpic:      INCBIN "gfx/pokemon/obelith/front.animated.2bpp.lz"
TendrillBackpic:       INCBIN "gfx/pokemon/tendrill/back.2bpp.lz"
YukittenFrontpic:    INCBIN "gfx/pokemon/yukitten/front.animated.2bpp.lz"
SnokageBackpic:    INCBIN "gfx/pokemon/snokage/back.2bpp.lz"
DunefinBackpic:    INCBIN "gfx/pokemon/dunefin/back.2bpp.lz"
MadrugasaBackpic:       INCBIN "gfx/pokemon/madrugasa/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
FarfetchDBackpic:    INCBIN "gfx/pokemon/farfetch_d/back.2bpp.lz"
PrawmateBackpic:     INCBIN "gfx/pokemon/prawmate/back.2bpp.lz"
WormeekBackpic:       INCBIN "gfx/pokemon/wormeek/back.2bpp.lz"
RadeonBackpic:       INCBIN "gfx/pokemon/radeon/back.2bpp.lz"
TobacoonBackpic:     INCBIN "gfx/pokemon/tobacoon/back.2bpp.lz"
EukubFrontpic:      INCBIN "gfx/pokemon/eukub/front.animated.2bpp.lz"
MajesdorBackpic:     INCBIN "gfx/pokemon/majesdor/back.2bpp.lz"
DoduoBackpic:        INCBIN "gfx/pokemon/doduo/back.2bpp.lz"
ShabbycatFrontpic:      INCBIN "gfx/pokemon/shabbycat/front.animated.2bpp.lz"
BobbiteBackpic:       INCBIN "gfx/pokemon/bobbite/back.2bpp.lz"
GigeratorBackpic:       INCBIN "gfx/pokemon/gigerator/back.2bpp.lz"
MossarreBackpic:        INCBIN "gfx/pokemon/mossarre/back.2bpp.lz"
ScaulterBackpic:     INCBIN "gfx/pokemon/scaulter/back.2bpp.lz"
NanuquaBackpic:      INCBIN "gfx/pokemon/nanuqua/back.2bpp.lz"
SandolphBackpic:    INCBIN "gfx/pokemon/sandolph/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
ShellderBackpic:     INCBIN "gfx/pokemon/shellder/back.2bpp.lz"
StinpeonBackpic:        INCBIN "gfx/pokemon/stinpeon/back.2bpp.lz"
SmuciousFrontpic:   INCBIN "gfx/pokemon/smucious/front.animated.2bpp.lz"
CocacobraBackpic:       INCBIN "gfx/pokemon/cocacobra/back.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"
KoaganBackpic:        INCBIN "gfx/pokemon/koagan/back.2bpp.lz"
CasanocteBackpic:     INCBIN "gfx/pokemon/casanocte/back.2bpp.lz"
SubcerosBackpic:     INCBIN "gfx/pokemon/subceros/back.2bpp.lz"
NoxromaeusBackpic:   INCBIN "gfx/pokemon/noxromaeus/back.2bpp.lz"
BiporkarBackpic:     INCBIN "gfx/pokemon/biporkar/back.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"
GoosaplingBackpic:      INCBIN "gfx/pokemon/goosapling/back.2bpp.lz"
BulbasaurFrontpic:   INCBIN "gfx/pokemon/bulbasaur/front.animated.2bpp.lz"
PeekeyeBackpic:      INCBIN "gfx/pokemon/peekeye/back.2bpp.lz"


SECTION "Pics 13", ROMX

MammothraBackpic:      INCBIN "gfx/pokemon/mammothra/back.2bpp.lz"
FurnitBackpic:       INCBIN "gfx/pokemon/furnit/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
PekoiBackpic:        INCBIN "gfx/pokemon/pekoi/back.2bpp.lz"
WiwrightBackpic:     INCBIN "gfx/pokemon/wiwright/back.2bpp.lz"
ScorchopprBackpic:   INCBIN "gfx/pokemon/scorchoppr/back.2bpp.lz"
CharmeleonBackpic:   INCBIN "gfx/pokemon/charmeleon/back.2bpp.lz"
OnionionBackpic:    INCBIN "gfx/pokemon/onionion/back.2bpp.lz"
WandelusFrontpic:       INCBIN "gfx/pokemon/wandelus/front.animated.2bpp.lz"
GiguardBackpic:      INCBIN "gfx/pokemon/giguard/back.2bpp.lz"
WormachoBackpic:     INCBIN "gfx/pokemon/wormacho/back.2bpp.lz"
FlurikenBackpic:      INCBIN "gfx/pokemon/fluriken/back.2bpp.lz"
HeracrossBackpic:    INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
DrassalBackpic:      INCBIN "gfx/pokemon/drassal/back.2bpp.lz"
WirigibleBackpic:    INCBIN "gfx/pokemon/wirigible/back.2bpp.lz"
JunobeBackpic:       INCBIN "gfx/pokemon/junobe/back.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
NoomsdayBackpic:        INCBIN "gfx/pokemon/noomsday/back.2bpp.lz"
ShuckleFrontpic:     INCBIN "gfx/pokemon/shuckle/front.animated.2bpp.lz"
MoperdorBackpic:     INCBIN "gfx/pokemon/moperdor/back.2bpp.lz"
StiklbratFrontpic:   INCBIN "gfx/pokemon/stiklbrat/front.animated.2bpp.lz"
CremigoFrontpic:     INCBIN "gfx/pokemon/cremigo/front.animated.2bpp.lz"
MoradayBackpic:         INCBIN "gfx/pokemon/moraday/back.2bpp.lz"
LeaffigyBackpic:      INCBIN "gfx/pokemon/leaffigy/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
KarenPic:            INCBIN "gfx/trainers/karen.2bpp.lz"
OnioniBackpic:     INCBIN "gfx/pokemon/onioni/back.2bpp.lz"
TentacruelBackpic:   INCBIN "gfx/pokemon/tentacruel/back.2bpp.lz"
HappigBackpic:    INCBIN "gfx/pokemon/happig/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
NimbocetusBackpic:      INCBIN "gfx/pokemon/nimbocetus/back.2bpp.lz"
RaichuBackpic:       INCBIN "gfx/pokemon/raichu/back.2bpp.lz"
YuggromiBackpic:    INCBIN "gfx/pokemon/yuggromi/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
PhanguardFrontpic:     INCBIN "gfx/pokemon/phanguard/front.animated.2bpp.lz"
ShrimpanziBackpic:     INCBIN "gfx/pokemon/shrimpanzi/back.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
ElectrodeFrontpic:   INCBIN "gfx/pokemon/electrode/front.animated.2bpp.lz"
PardnerBackpic:    INCBIN "gfx/pokemon/pardner/back.2bpp.lz"


SECTION "Pics 14", ROMX

YuefoeBackpic:      INCBIN "gfx/pokemon/yuefoe/back.2bpp.lz"
WendigauntFrontpic:     INCBIN "gfx/pokemon/wendigaunt/front.animated.2bpp.lz"
AllseeraphBackpic:      INCBIN "gfx/pokemon/allseeraph/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
KalkolaBackpic:      INCBIN "gfx/pokemon/kalkola/back.2bpp.lz"
DolmiteBackpic:      INCBIN "gfx/pokemon/dolmite/back.2bpp.lz"
BowlideBackpic:      INCBIN "gfx/pokemon/bowlide/back.2bpp.lz"
PocalyptusBackpic:    INCBIN "gfx/pokemon/pocalyptus/back.2bpp.lz"
MothomenBackpic:   INCBIN "gfx/pokemon/mothomen/back.2bpp.lz"
MeowtainBackpic:     INCBIN "gfx/pokemon/meowtain/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
BlastoiseBackpic:    INCBIN "gfx/pokemon/blastoise/back.2bpp.lz"
MaulzerBackpic:   INCBIN "gfx/pokemon/maulzer/back.2bpp.lz"
TyrogueBackpic:      INCBIN "gfx/pokemon/tyrogue/back.2bpp.lz"
DolmiteFrontpic:     INCBIN "gfx/pokemon/dolmite/front.animated.2bpp.lz"
YagagarasuBackpic:       INCBIN "gfx/pokemon/yagagarasu/back.2bpp.lz"
SwazzageBackpic:    INCBIN "gfx/pokemon/swazzage/back.2bpp.lz"
MissingnoBackpic:    INCBIN "gfx/pokemon/missingno/back.2bpp.lz"
EyechosisBackpic:     INCBIN "gfx/pokemon/eyechosis/back.2bpp.lz"
CharizardBackpic:    INCBIN "gfx/pokemon/charizard/back.2bpp.lz"
BundegrafBackpic:      INCBIN "gfx/pokemon/bundegraf/back.2bpp.lz"
BobbitrapBackpic:     INCBIN "gfx/pokemon/bobbitrap/back.2bpp.lz"
PurraatzleBackpic:       INCBIN "gfx/pokemon/purraatzle/back.2bpp.lz"
WartortleBackpic:    INCBIN "gfx/pokemon/wartortle/back.2bpp.lz"
CantaloneBackpic:    INCBIN "gfx/pokemon/cantalone/back.2bpp.lz"
StratowarFrontpic:   INCBIN "gfx/pokemon/stratowar/front.animated.2bpp.lz"
NomsabreBackpic:     INCBIN "gfx/pokemon/nomsabre/back.2bpp.lz" ;orig raticate
VulpixBackpic:       INCBIN "gfx/pokemon/vulpix/back.2bpp.lz"
WyrmometerBackpic:        INCBIN "gfx/pokemon/wyrmometer/back.2bpp.lz"
GanzerkerBackpic:      INCBIN "gfx/pokemon/ganzerker/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
VoyapodBackpic:      INCBIN "gfx/pokemon/voyapod/back.2bpp.lz"
PikachuBackpic:      INCBIN "gfx/pokemon/pikachu/back.2bpp.lz"
BellocerosFrontpic:      INCBIN "gfx/pokemon/belloceros/front.animated.2bpp.lz"
YuesbiBackpic:       INCBIN "gfx/pokemon/yuesbi/back.2bpp.lz"
StiklbratBackpic:     INCBIN "gfx/pokemon/stiklbrat/back.2bpp.lz"
HelactalFrontpic:       INCBIN "gfx/pokemon/helactal/front.animated.2bpp.lz"
NavigazerBackpic:      INCBIN "gfx/pokemon/navigazer/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
OddittenFrontpic:      INCBIN "gfx/pokemon/odditten/front.animated.2bpp.lz"
NyalleyBackpic:     INCBIN "gfx/pokemon/nyalley/back.2bpp.lz"
ElephootBackpic:      INCBIN "gfx/pokemon/elephoot/back.2bpp.lz"
PlantennaBackpic:    INCBIN "gfx/pokemon/plantenna/back.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
LamseedBackpic:       INCBIN "gfx/pokemon/lamseed/back.2bpp.lz"

SECTION "Pics 15", ROMX

Ma_0Backpic:       INCBIN "gfx/pokemon/ma_0/back.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/oak.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
MuminiFrontpic:     INCBIN "gfx/pokemon/mumini/front.animated.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
ZeppliumBackpic:          INCBIN "gfx/pokemon/zepplium/back.2bpp.lz"
DelibirdBackpic:     INCBIN "gfx/pokemon/delibird/back.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
MagikarpBackpic:     INCBIN "gfx/pokemon/magikarp/back.2bpp.lz"
GrubboidBackpic:      INCBIN "gfx/pokemon/grubboid/back.2bpp.lz"
SneaselBackpic:      INCBIN "gfx/pokemon/sneasel/back.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
BismuttBackpic:      INCBIN "gfx/pokemon/bismutt/back.2bpp.lz"
IvysaurBackpic:      INCBIN "gfx/pokemon/ivysaur/back.2bpp.lz"
SlowbroBackpic:      INCBIN "gfx/pokemon/slowbro/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
ExotunityBackpic:      INCBIN "gfx/pokemon/exotunity/back.2bpp.lz"
SakuronnaBackpic:      INCBIN "gfx/pokemon/sakuronna/back.2bpp.lz"
SlaatelBackpic:        INCBIN "gfx/pokemon/slaatel/back.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/grunt_f.2bpp.lz"
OscurasaFrontpic:      INCBIN "gfx/pokemon/oscurasa/front.animated.2bpp.lz"
HornampaBackpic:     INCBIN "gfx/pokemon/hornampa/back.2bpp.lz"
HoOhBackpic:         INCBIN "gfx/pokemon/ho_oh/back.2bpp.lz"
AmanigoBackpic:      INCBIN "gfx/pokemon/amanigo/back.2bpp.lz"
MewBackpic:          INCBIN "gfx/pokemon/mew/back.2bpp.lz"
UpwhaleBackpic:       INCBIN "gfx/pokemon/upwhale/back.2bpp.lz"
AmbinniBackpic:      INCBIN "gfx/pokemon/ambinni/back.2bpp.lz"
AerodactylBackpic:   INCBIN "gfx/pokemon/aerodactyl/back.2bpp.lz"
HoatoxicFrontpic:    INCBIN "gfx/pokemon/hoatoxic/front.animated.2bpp.lz"
MumagnusBackpic:     INCBIN "gfx/pokemon/mumagnus/back.2bpp.lz"
OrgnomeBackpic:      INCBIN "gfx/pokemon/orgnome/back.2bpp.lz"
SprunnyBackpic:     INCBIN "gfx/pokemon/sprunny/back.2bpp.lz"
DolmesaBackpic:      INCBIN "gfx/pokemon/dolmesa/back.2bpp.lz"
HoplaqueBackpic:     INCBIN "gfx/pokemon/hoplaque/back.2bpp.lz"
EspeonBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
HoatotFrontpic:      INCBIN "gfx/pokemon/hoatot/front.animated.2bpp.lz"
FursaBackpic:        INCBIN "gfx/pokemon/fursa/back.2bpp.lz"   ;orig totodile
ZasterBackpic:     INCBIN "gfx/pokemon/zaster/back.2bpp.lz"
PepofferBackpic:     INCBIN "gfx/pokemon/pepoffer/back.2bpp.lz"
PitayrantBackpic:    INCBIN "gfx/pokemon/pitayrant/back.2bpp.lz"
UltramanPic:		INCBIN "gfx/trainers/ultraman.2bpp.lz"


SECTION "Pics 16", ROMX

BellocerosBackpic:       INCBIN "gfx/pokemon/belloceros/back.2bpp.lz"
GnomercyBackpic:     INCBIN "gfx/pokemon/gnomercy/back.2bpp.lz"
TodescoolBackpic:       INCBIN "gfx/pokemon/todescool/back.2bpp.lz"
OkamikazeBackpic:    INCBIN "gfx/pokemon/okamikaze/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
SappuraBackpic:    INCBIN "gfx/pokemon/sappura/back.2bpp.lz"
TranquielFrontpic:   INCBIN "gfx/pokemon/tranquiel/front.animated.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
ScruffruitBackpic:   INCBIN "gfx/pokemon/scruffruit/back.2bpp.lz"
SqueenieBackpic:         INCBIN "gfx/pokemon/squeenie/back.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
PolyroBackpic:     INCBIN "gfx/pokemon/polyro/back.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/jasmine.2bpp.lz"
ShreddrakeBackpic:       INCBIN "gfx/pokemon/shreddrake/back.2bpp.lz"
HivemaimFrontpic:    INCBIN "gfx/pokemon/hivemaim/front.animated.2bpp.lz"
CaddisicleBackpic:   INCBIN "gfx/pokemon/caddisicle/back.2bpp.lz"
AstrotomBackpic:     INCBIN "gfx/pokemon/astrotom/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
JolteonBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
BuzzlingFrontpic:    INCBIN "gfx/pokemon/buzzling/front.animated.2bpp.lz"
ShabbycatBackpic:    INCBIN "gfx/pokemon/shabbycat/back.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
GrimpactBackpic:     INCBIN "gfx/pokemon/grimpact/back.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
QwailBackpic:        INCBIN "gfx/pokemon/qwail/back.2bpp.lz"
PhanguardBackpic:    INCBIN "gfx/pokemon/phanguard/back.2bpp.lz"
MandelblobBackpic:       INCBIN "gfx/pokemon/mandelblob/back.2bpp.lz"
MagbyBackpic:        INCBIN "gfx/pokemon/magby/back.2bpp.lz"
DragonairBackpic:    INCBIN "gfx/pokemon/dragonair/back.2bpp.lz"
ZapdosBackpic:       INCBIN "gfx/pokemon/zapdos/back.2bpp.lz"
CigerillarBackpic:   INCBIN "gfx/pokemon/cigerillar/back.2bpp.lz" ;orig chiko
BaafometBackpic:      INCBIN "gfx/pokemon/baafomet/back.2bpp.lz"
StranglureBackpic:     INCBIN "gfx/pokemon/stranglure/back.2bpp.lz"
CalarmouriBackpic:      INCBIN "gfx/pokemon/calarmouri/back.2bpp.lz"
PurrdleBackpic:      INCBIN "gfx/pokemon/purrdle/back.2bpp.lz"
GwubbyFrontpic:      INCBIN "gfx/pokemon/gwubby/front.animated.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
CharmanderBackpic:   INCBIN "gfx/pokemon/charmander/back.2bpp.lz"
CuttleBackpic:      INCBIN "gfx/pokemon/cuttle/back.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"



SECTION "Pics 17", ROMX

ParasBackpic:        INCBIN "gfx/pokemon/paras/back.2bpp.lz"
GanzorahBackpic:     INCBIN "gfx/pokemon/ganzorah/back.2bpp.lz"
TentacoolBackpic:    INCBIN "gfx/pokemon/tentacool/back.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
BulbasaurBackpic:    INCBIN "gfx/pokemon/bulbasaur/back.2bpp.lz"
SmoochumBackpic:     INCBIN "gfx/pokemon/smoochum/back.2bpp.lz"
WandelusBackpic:        INCBIN "gfx/pokemon/wandelus/back.2bpp.lz"
SnoverdoseBackpic:     INCBIN "gfx/pokemon/snoverdose/back.2bpp.lz"
LawnieBackpic:       INCBIN "gfx/pokemon/lawnie/back.2bpp.lz"
DumbloonBackpic:       INCBIN "gfx/pokemon/dumbloon/back.2bpp.lz"
ShamselBackpic:      INCBIN "gfx/pokemon/shamsel/back.2bpp.lz"
FurdobaBackpic:      INCBIN "gfx/pokemon/furdoba/back.2bpp.lz"
PeautyBackpic:       INCBIN "gfx/pokemon/peauty/back.2bpp.lz"
PeacolderBackpic:       INCBIN "gfx/pokemon/peacolder/back.2bpp.lz"
BuzzlingBackpic:     INCBIN "gfx/pokemon/buzzling/back.2bpp.lz"
VoltorbFrontpic:     INCBIN "gfx/pokemon/voltorb/front.animated.2bpp.lz"
AvatriceBackpic:        INCBIN "gfx/pokemon/avatrice/back.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/pryce.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
IgnagaBackpic:        INCBIN "gfx/pokemon/ignaga/back.2bpp.lz"
PolitoedBackpic:     INCBIN "gfx/pokemon/politoed/back.2bpp.lz"
DragoniteBackpic:    INCBIN "gfx/pokemon/dragonite/back.2bpp.lz"
MothoBackpic:    INCBIN "gfx/pokemon/motho/back.2bpp.lz"
SqwuckyFrontpic:        INCBIN "gfx/pokemon/sqwucky/front.animated.2bpp.lz"
SmothereneBackpic:     INCBIN "gfx/pokemon/smotherene/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
SmuciousBackpic:    INCBIN "gfx/pokemon/smucious/back.2bpp.lz"
ObelithBackpic:       INCBIN "gfx/pokemon/obelith/back.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
HoatoxicBackpic:     INCBIN "gfx/pokemon/hoatoxic/back.2bpp.lz"
RespectreBackpic:    INCBIN "gfx/pokemon/respectre/back.2bpp.lz"
TranquielBackpic:       INCBIN "gfx/pokemon/tranquiel/back.2bpp.lz"
CrobatBackpic:       INCBIN "gfx/pokemon/crobat/back.2bpp.lz"
OdditullyBackpic:      INCBIN "gfx/pokemon/odditully/back.2bpp.lz"
AmpharosBackpic:     INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
StratowarBackpic:    INCBIN "gfx/pokemon/stratowar/back.2bpp.lz"
SateliskBackpic:    INCBIN "gfx/pokemon/satelisk/back.2bpp.lz"
SidficiousBackpic:    INCBIN "gfx/pokemon/sidficious/back.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
OscurasaBackpic:       INCBIN "gfx/pokemon/oscurasa/back.2bpp.lz"
WendigauntBackpic:      INCBIN "gfx/pokemon/wendigaunt/back.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
IcosahedBackpic:   INCBIN "gfx/pokemon/icosahed/back.2bpp.lz"
ArticunoBackpic:     INCBIN "gfx/pokemon/articuno/back.2bpp.lz"
HelactalBackpic:        INCBIN "gfx/pokemon/helactal/back.2bpp.lz"
HoatotBackpic:       INCBIN "gfx/pokemon/hoatot/back.2bpp.lz"


SECTION "Pics 18", ROMX

OddittenBackpic:       INCBIN "gfx/pokemon/odditten/back.2bpp.lz"
TaurosBackpic:       INCBIN "gfx/pokemon/tauros/back.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
AntpyreBackpic:      INCBIN "gfx/pokemon/antpyre/back.2bpp.lz"
VoltorbBackpic:      INCBIN "gfx/pokemon/voltorb/back.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
KrakentoaBackpic:      INCBIN "gfx/pokemon/krakentoa/back.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
VegetebaaBackpic:    INCBIN "gfx/pokemon/vegetebaa/back.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
SqwuckyBackpic:         INCBIN "gfx/pokemon/sqwucky/back.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
CairnivoreBackpic:        INCBIN "gfx/pokemon/cairnivore/back.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
MuminiBackpic:      INCBIN "gfx/pokemon/mumini/back.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
ClibbleBackpic:         INCBIN "gfx/pokemon/clibble/back.2bpp.lz"
ScorperorBackpic:       INCBIN "gfx/pokemon/scorperor/back.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
ForretressBackpic:   INCBIN "gfx/pokemon/forretress/back.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownIBackpic:       INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownRBackpic:       INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"


SECTION "Pics 19", ROMX

PilfoardFrontpic:    INCBIN "gfx/pokemon/pilfoard/front.animated.2bpp.lz"
PilfoardBackpic:	 INCBIN "gfx/pokemon/pilfoard/back.2bpp.lz"
GwubbyBackpic:     INCBIN "gfx/pokemon/gwubby/back.2bpp.lz"
RaikouBackpic:       INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
SnowupBackpic:     INCBIN "gfx/pokemon/snowup/back.2bpp.lz"
CremigoBackpic:      INCBIN "gfx/pokemon/cremigo/back.2bpp.lz"
SquirtleBackpic:     INCBIN "gfx/pokemon/squirtle/back.2bpp.lz"
ShuckleBackpic:      INCBIN "gfx/pokemon/shuckle/back.2bpp.lz"
JaddiceBackpic:      INCBIN "gfx/pokemon/jaddice/back.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
MissteriaBackpic:     INCBIN "gfx/pokemon/missteria/back.2bpp.lz"
AttackoBackpic:    INCBIN "gfx/pokemon/attacko/back.2bpp.lz"
MoneumennBackpic:      INCBIN "gfx/pokemon/moneumenn/back.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"
NimboremBackpic:       INCBIN "gfx/pokemon/nimborem/back.2bpp.lz"
EelkieBackpic:      INCBIN "gfx/pokemon/eelkie/back.2bpp.lz"
FluffruitBackpic:       INCBIN "gfx/pokemon/fluffruit/back.2bpp.lz"
QwallopBackpic:       INCBIN "gfx/pokemon/qwallop/back.2bpp.lz"
HabbleBackpic:       INCBIN "gfx/pokemon/habble/back.2bpp.lz"
DratiniBackpic:      INCBIN "gfx/pokemon/dratini/back.2bpp.lz"
ElectrodeBackpic:    INCBIN "gfx/pokemon/electrode/back.2bpp.lz"
SnosebleedBackpic:  INCBIN "gfx/pokemon/snosebleed/back.2bpp.lz"
HivemaimBackpic:    INCBIN "gfx/pokemon/hivemaim/back.2bpp.lz"
HexahedBackpic:   	INCBIN "gfx/pokemon/hexahed/back.2bpp.lz"
EukubBackpic:       INCBIN "gfx/pokemon/eukub/back.2bpp.lz"
UnownDBackpic:      INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"
WizardPic:        	INCBIN "gfx/trainers/wizard.2bpp.lz"
CheaterPic:       	INCBIN "gfx/trainers/cheater.2bpp.lz"
EnforcerPic:	  	INCBIN "gfx/trainers/enforcer.2bpp.lz"
AthleteFPic:	  	INCBIN "gfx/trainers/athlete_f.2bpp.lz"
AthleteMPic:	  	INCBIN "gfx/trainers/athlete_m.2bpp.lz"
FanaticRedPic:	  	INCBIN "gfx/trainers/fanatic_red.2bpp.lz"
FanaticBluePic:   	INCBIN "gfx/trainers/fanatic_blue.2bpp.lz"
WarriorPic:       	INCBIN "gfx/trainers/warrior.2bpp.lz"
RadicalPic:		  	INCBIN "gfx/trainers/radical.2bpp.lz"
SalarymanPic: 		INCBIN "gfx/trainers/salaryman.2bpp.lz"
EngineerPic:		INCBIN "gfx/trainers/engineer.2bpp.lz"
SkepticPic:			INCBIN "gfx/trainers/skeptic.2bpp.lz"
ImakuniPic:			INCBIN "gfx/trainers/imakuni.2bpp.lz"


; Sections "Pics 20" to "Pics 24" are not used for any graphics,
; but entries for their banks exist in FixPicBank (see engine/gfx/load_pics.asm).

SECTION "Pics 20", ROMX

SECTION "Pics 21", ROMX

SECTION "Pics 22", ROMX

SECTION "Pics 23", ROMX

SECTION "Pics 24", ROMX
